### ISSUE TITLE
Barebone repo and CI

### ISSUE THREAD

**Issue by maximelubin** [ronomon/reed-solomon#3]
Do what needs to be done. Have a clean start

**Comment by jorangreef** [comment]
> Do what needs to be done. Have a clean start

Can you provide a bit more detail as to what you mean or would like to see?

**Comment by maximelubin** [comment]
Ah! Seems I used the wrong repo. I was tasked to kickstart several of them for my work and I confused tabs. Really sorry about the noise.

**Comment by jorangreef** [comment]
Thanks, no worries!
