### ISSUE TITLE
pure JS implementation that can used on the browser ?

### ISSUE THREAD

**Issue by ambati2002** [ronomon/reed-solomon#6]
Hi,
I am trying to find an implementation that can be used on browser. The goal is to have the erasure coding be performed on the browser and upload the multiple splits to multiple servers. 

Any ideas or recommendations ?

**Comment by jorangreef** [comment]
You could rewrite the contents of binding.cc in Javascript. It maps easily and directly to Javascript, you would just need to replace the pointer slices with buffers + offsets.
